### ISSUE TITLE
Update latest rockspec for Moses

### ISSUE THREAD

**Issue by Yonaba** [rocks-moonscript-org/moonrocks-mirror#1]
The rockspec for the latest version of [Moses](http://github.com/Yonaba/Moses) was fixed (see [here](http://luarocks.org/modules/yonaba/moses/1.6.0-1)). However, the copy on this mirror has not been updated, see [here](https://github.com/rocks-moonscript-org/moonrocks-mirror/blob/master/moses-1.6.0-1.rockspec).

**Comment by leafo** [comment]
The backup system isn't aware of file changes. I refreshed the entire backup: https://github.com/rocks-moonscript-org/moonrocks-mirror/commit/04a4580d96a784ea2a6d2286971f07758ae644f5

**Comment by Yonaba** [comment]
Much thanks, @leafo.
